### ISSUE TITLE
Fix the MenuViewControllers flow to Welcome/Login Navigation Controller

### ISSUE THREAD

**Issue by sbrshkappa** [PetPal/PetPal#11] opened 2017-04-29 19:11 UTC
There was something wrong with the way the Menu View Controller was loading and the story board was configured. I was also seeing that the code is now jumping directly to the Requests View Controller, was this intended behavior? If yes, can you create an issue for this and  explain the new flow?

I'm assuming this was an merging error.

![image](https://cloud.githubusercontent.com/assets/4317453/25558115/d07ebbb0-2cd4-11e7-83de-e451596b6e99.png)

**Comment by linghao2** [comment] 2017-04-29 19:41
Rui was working on the Login view. I needed the RequestViewController to be accessible so I can test my code. 
Rui, what was the intended behavior?

**Comment by sbrshkappa** [comment] 2017-04-29 19:43
I think we have a RequestView Storyboard right now. Just curious, when do we create a new storyboard vs a new view controllers?

**Comment by linghao2** [comment] 2017-04-29 20:54
I put the RequestViewController in the Request.storyboard. I was trying to minimize merge conflicts. Is this bug still an issue? It will be fixed once I implement the HomeViewController.

**Comment by mr618show** [comment] 2017-04-29 22:05
The bug was fixed. the name of "loginViewController" no long exists because I changed it to "WelcomeViewController" in identifier in storyboard and missed update it here.

**Closed as completed** 2017-04-29 22:05 UTC
Labels: bug
